### ISSUE TITLE
怎麼不是用 Gitbook 來進行完整的編輯？

### ISSUE THREAD

**Issue by deduce** [kdchang/reactjs101#18]
as title 這樣應該會比較方便閱讀 & 擴散？

我剛剛在 Gitbook 上點了結果是連回 GitHub？

不過這本書非常棒，good job

**Comment by ycjwu** [comment]
gitbook 上閱讀確實比較方便，有需要的話我可以幫忙移轉

**Comment by kdchang** [comment]
@deduce 謝謝學長的建議和肯定：）

也謝謝 @ycjwu 願意協助幫忙！

之前有考慮直接放 Gitbook 但想說先在 Github 沈澱一下內容，等最近更完整成熟後就會放過去囉！

**Comment by deduce** [comment]
酷唷，加油！
