### ISSUE TITLE
error

### ISSUE THREAD

**Issue by AnnaHui** [kdchang/reactjs101#2]
ch3.
ReactDOM.render(<MyComponent/>, document.getElmentById('app'));
應該是
ReactDOM.render(<MyComponent/>, document.getElementById('app'));

謝謝您提供這麼好的教學文件.

**Comment by kdchang** [comment]
@AnnaHui 謝謝您的提醒，已經修正囉～

很高興我寫的書對妳有幫助，若有任何建議或提醒都歡迎和我說喔，也歡迎分享給有興趣的朋友們，謝謝您：）
