### ISSUE TITLE
JSX 簡明入門教學指南中書寫錯誤

### ISSUE THREAD

**Issue by kingzez** [kdchang/reactjs101#21]
https://github.com/kdchang/reactjs101/blob/master/Ch03/react-jsx-introduction.md
一、使用 JSX 的好處 > 1. 提供更加語意化且易懂的標籤中
```
<form class="messageBox">
  <textarea></teextarea>
  <button type="submit"></button>
</from>
```

`<teextarea>` -> `<textarea>` 標籤拼寫錯誤，雖然不影響閱讀，不過還是提醒一下。

**Comment by kdchang** [comment]
@kingzez 已經修正囉，感謝提醒：）

**Comment by bobby1991qw** [comment]
你好，能否在router的章节中加上动态路由的部分呢？
