### ISSUE TITLE
#Ch09

### ISSUE THREAD

**Issue by stefaniepei** [kdchang/reactjs101#22]
----------------------------------------------------------------------------------------------
以下是 src/components/ResultPage/ResultPage.js，將 userId 當作 props 傳給 <GithubBox />：

import React from 'react';
**# import GithubBox from '../../components/GithubBox';**

... 
**# GithubBox data={props.data} userId={props.location.query.userId} **  
...

在code裏面，
1.import GithubBox from '../../components/GithubBox'; 應改成上述加粗部分內容
2.GithubBox data={props.data} userId={props.location.query.userId}   應改成應改成上述加粗部分內容

最後，非常感謝您提供的這份教學書，給予了我很大的幫助!!!

**Comment by kdchang** [comment]
@stefaniepei 感謝您的肯定和提醒，已經修復囉，也歡迎分享給有興趣的朋友：）
