### ISSUE TITLE
Ch03 ReactJS 與 Component 設計入門介紹 typo

### ISSUE THREAD

**Issue by b12031106** [kdchang/reactjs101#23]
中間介紹 Functional Component 寫法的範例：
```
2. 使用 Funtional Component 寫法（單純地 render UI 的 stateless components....
```
以及程式碼中的註解部分

```
// 使用 arror function 來設計 Funtional Component 讓 UI 設計更單純...
```
中的  `arror` 是否應該為 `arrow` ? `Funtional` 是否應該為 `Functional` ?

感謝您的無私分享，這份教學非常詳盡實用！

**Comment by appleboy** [comment]
@b12031106 #24 PR

**Comment by kdchang** [comment]
@b12031106 謝謝你的肯定，還有很多需要學習的，也歡迎分享給有興趣的朋友喔：）

怪了，我記得之前有修正過了？xD  感謝 @appleboy 前輩協助：）

**Comment by bobby1991qw** [comment]
你好，看了你的这份教程感觉帮助很大。  能否在router章节中加入动态路由的使用呢

**Comment by kdchang** [comment]
@b12031106 感謝您的支持和肯定，可否請您[另外開一個 issue](https://github.com/kdchang/reactjs101/issues) 呢？
由於 React Router 技術變化快速，我再找時間研究一下需要補充哪些內容，謝謝：）

**Comment by b12031106** [comment]
不是我呀XD 幫你 tag 他 @bobby1991qw

**Comment by kdchang** [comment]
@b12031106 sorry ，tag 錯了，感謝xDD
