### ISSUE TITLE
使用 babel-standalone 取代 babel-core/browser？

### ISSUE THREAD

**Issue by chentsulin** [kdchang/reactjs101#3]
現在大家都用 babel 6 了，可以避免 babel 5 一些不相容的東西

相關連結：https://github.com/facebook/react/pull/7668

**Comment by kdchang** [comment]
@chentsulin Hi 承澤～謝謝你的提醒！不好意思因為時間太趕，一時沒有留意，晚點回去修正一下。還有很多需要學習的，還請多多指教～：）

**Comment by kdchang** [comment]
@chentsulin fixed, thanks a lot:)
