### ISSUE TITLE
一处拼写错误

### ISSUE THREAD

**Issue by yueshuiniao** [kdchang/reactjs101#33]
https://github.com/carlleton/reactjs101/blob/zh-CN/Ch03/react-jsx-introduction.md  ===>  3. 结合原生 JavaScript 语法  ===>   class HelloMessage extends React.Compoent {    此处Component少了一个字母，代码运行不了

**Comment by kdchang** [comment]
@yueshuiniao 感謝，已修復！

@carlleton 也請協助更新一下簡體中文版，謝謝！

**Comment by carlleton** [comment]
@kdchang 简体中文版已经修复

**Comment by kdchang** [comment]
@carlleton  cool. thanks a lot:))
