### ISSUE TITLE
webpack在babel的設定上似乎有多餘的設定

### ISSUE THREAD

**Issue by fenixwu** [kdchang/reactjs101#34]
.babelrc和query擇一設定即可。

**Comment by kdchang** [comment]
@fenixwu  嗯嗯，感謝提醒～
之前是在第二章環境設定說明時使用，目前有先調整和更新說明[在根目錄設定 webpack.config.js](https://github.com/kdchang/reactjs101/blob/master/Ch02/webpack-dev-enviroment.md)
