### ISSUE TITLE
請教eslitrc設置

### ISSUE THREAD

**Issue by chienfuchen32** [kdchang/reactjs101#38]
你好 非常謝謝你寫的React教學!讓我受益良多
目前我是使用sublime開發環境，
從一開始章節的內容開始我設置.eslintrc都是設置 
[http://eddychang.me/blog/javascript/51-sublime-text-3-react.html](url)，
但是讀到實戰教學：用 React + Router + Redux + ImmutableJS 寫一個 Github 查詢應用時，
依照source code的.eslintrc設置或是教學文的.eslintrc設置皆會有不正常的紅字出現在環境中，
直到我把檔案更新如下，才稍微正常一些，想請教是我的開發環境出了一些問題嗎?謝謝

```
{
  // use babel-eslint for parsing!
  "parser": "babel-eslint",
  "env": {
    // for browser
    "browser": true,
    // in CommonJS
    "node": true
  },
  // some rule options:
  "rules": {
    "quotes": [2, "single"],
    "eol-last": [0],
    "no-mixed-requires": [0],
    "no-underscore-dangle": [0]
  }
}
```

**Comment by appleboy** [comment]
@chienfuchen32 程式碼可以用 markdown 格式包起來，會比較清楚

**Comment by kdchang** [comment]
@chienfuchen32 我晚點確認一下是不是有地方沒改到，sorry 最近事情剛好比較忙
@appleboy 感謝前輩補充！
