### ISSUE TITLE
Props、State、Refs 与表单处理

### ISSUE THREAD

**Issue by caixianglin** [kdchang/reactjs101#39]
Props、State、Refs 与表单处理-章节，最后一个markdown例子本地运行出错，浏览器不能解析，除非引入

```
<script src="./build/browser.min.js"></script>
<script type="text/babel" src="./app.js"></script>}
```

才能正常运行解析

**Comment by caixianglin** [comment]
哦，我的错，使用 browserify 或 webpack 等 CommonJS bundler 并整合 babel 预处理就直接可以运行了，但是希望作者注释说明一下，浏览器解析方式下代码应该加上上面两行

**Comment by kdchang** [comment]
@caixianglin 好的，我晚點補上，謝謝您的建議：）

**Comment by kdchang** [comment]
@caixianglin  fix ，thanks a lot:)
