### ISSUE TITLE
CH07 - There is no TodoHeader/TodoList containter yet

### ISSUE THREAD

**Issue by nickkfwong** [kdchang/reactjs101#53]
Main.js does not work and I have no idea how to continue on that. Thanks

**Comment by kdchang** [comment]
sorry, which example do you refer ? thanks :)

**Comment by nickkfwong** [comment]
CH7 'Redux 實戰入門'

from this line: 
> '其中 src/components/Main/Main.js 是 Stateless Component，負責所有 View 的進入點。'

Although I read some other documentation and finally make it work, the sample in CH7 will work only until we finish CH8.
