### ISSUE TITLE
preLoaders 造成webpack無法執行?

### ISSUE THREAD

**Issue by dn-la** [kdchang/reactjs101#64]
嗨, 您好 
在學習CH05的時候,遇到一個問題
發現在 `webpack.config.js` 裡面的 `module: {
    preLoaders: [
      {
  ...
      }
    ],` 
似乎造成webpack錯誤 無法執行

如下terminal截圖
![image](https://cloud.githubusercontent.com/assets/15864413/23501578/59c209e2-ff6f-11e6-9333-6be28de35aad.png)

稍微查了一下,[解決方法](https://github.com/angular/angular-cli/issues/2234)是用 `webpack@2.1.0-beta.22` 版本
我目前是 `"webpack": "^2.2.0",` _應該也是latest的吧...._

可以請問一下您目前有遇到這個問題嗎~~?
是可以有其他解法或 還是就使用stable版本的webpack呢

**Comment by s1012602** [comment]
我在學習ch09遇到和你一樣的問題

**Comment by DeAnnHuang** [comment]
@s1012602  我後來就直接使用比較低版本的webpack了 or 直接clone 檔案下來學習

**Comment by headhsu2568** [comment]
使用 webpack 2.3.3, 可以試試看以下這個寫法:
PreLoader 放在 rules 中有設定 enforce: 'pre' 的 block:

![image](https://cloud.githubusercontent.com/assets/652248/24792946/9dc2357c-1bb2-11e7-8cac-acbbd775bb34.png)
