### ISSUE TITLE
typo?

### ISSUE THREAD

**Issue by rickyteng** [kdchang/reactjs101#7]
「以上就是讀者 React 在生態系遊走時會出現各種關主」

-->

「以上就是讀者 React 在生態系遊走時會出現各種關卡」

**Comment by appleboy** [comment]
@rickyteng Send new PR #8

**Comment by kdchang** [comment]
感謝 @rickyteng @appleboy ：）

這句當初寫的時候可能沒寫好，我再來潤潤看xD

=> 以上就是讀者在 React 生態系遊走時會遇到的各種關卡
