### ISSUE TITLE
React Router ch5 unable to resolve path

### ISSUE THREAD

**Issue by schrodog** [kdchang/reactjs101#72]
你好， 我在使用webpack 2.4.1 時跟ch5 教程到最後 npm start 未能load components 的moudle

![screenshot from 2017-05-06 12-07-48](https://cloud.githubusercontent.com/assets/16360247/25769762/e0af7530-3254-11e7-9482-d2dba72f2d11.png)

未知解決方法是什麼？ 謝謝

**Comment by schrodog** [comment]
Problem solved. Not yet creating "index.js" and "xxx.js" in corresponding directories.

**Comment by kdchang** [comment]
@schrodog cool. cheer up :)
